<?php

namespace common\models;

use Yii;
use common\models\Customer;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "maintenance".
 *
 * @property int $id
 * @property int $client_id
 * @property int $store_id
 * @property int $item_count
 * @property string|null $client_note
 * @property string $status
 * @property float|null $amount_paid
 * @property int $service_center_id
 * @property string|null $maintenance_note
 * @property float $maintenance_cost
 * @property float $maintenance_cost_time
 * @property float $amount_paid_time
 * @property float|null $cost_difference
 * @property int $created_at
 * @property int $created_by
 * @property int|null $updated_at
 * @property int|null $updated_by
 */
class Maintenance extends \common\components\BaseModel
{
    
    const STATUS_ACTIVE = 1;
    const STATUS_WAIGHT = 2;
    const STATUS_CONFIRM = 3;
    const STATUS_COMPLET = 4;
    const statusArray = [
        self::STATUS_ACTIVE=>'بانتظار الصيانة',
        self::STATUS_WAIGHT=>'قيد الصيانة',
        self::STATUS_CONFIRM=>'تم الاستلام من الصيانة ',
        self::STATUS_COMPLET=>'تم التسليم للعميل مكتمل',
    ];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'maintenance';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['client_id','product_name', 'item_count', 'status', 'service_center_id', 'store_id'], 'required'],
            [['client_id', 'item_count', 'service_center_id', 'created_by'], 'integer'],
            [['client_note', 'maintenance_note'], 'string'],
            [['created_at', 'updated_at'], 'integer'],
            [['updated_by','status'], 'integer'],
            [['maintenance_cost_time','amount_paid_time'], 'safe'],
            [['amount_paid'],'required', 'when' => function($model) {
                if($this->status == 4) 
                {
                    return true;
                }
                return false;
            }],
            [['maintenance_cost'],'required', 'when' => function($model) {
                if($this->status >= 3) 
                {
                    return true;
                }
                return false;
            }],
        ];
    }
    
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'الرقم',
            'client_id'  => 'اسم العميل',
            'store_id'  => 'المحل',
            'product_name' => 'اسم المادة',
            'item_count' => 'العدد',
            'client_note' => ' ملاحظة العميل  ',
            'status' => 'حالة الطلب',
            'amount_paid' => ' المبلغ المدفوع من العميل ',
            'service_center_id' => 'مركز الصيانة',
            'maintenance_note' => 'ملاحظة الصيانة',
            'maintenance_cost' => 'تكلفة الصيانة',
            'cost_difference' => 'فرق التكلفة',
            'created_at' =>  'تاريخ الانشاء',
            'created_by' =>  'الشخص المنشئ',
            'updated_at' =>  'تاريخ التعديل',
            'updated_by' =>  'الشخص المعدل',
        ];
    }
    public function getServiceCenter()
    {
        return $this->hasOne(ServiceCenter::className(), ['id' => 'service_center_id']);
    }
    public function getClient()
    { 
        return $this->hasOne(Customer::class, ['id' => 'client_id']);
    }
    public function getStoreTitle()
    {
        return Store::findOne($this->store_id)->name;
    }
    public function beforeSave($insert)
    {

        if ($this->isAttributeChanged('maintenance_cost')) {
            // Set the repayment_date field to the current date and time
            $this->maintenance_cost_time = time();
        }
        if ($this->isAttributeChanged('amount_paid')) {
            // Set the repayment_date field to the current date and time
            $this->amount_paid_time = time();
        }
       
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
