<?php

namespace common\models;

use common\components\Constants;
use common\components\CustomFunc;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;
use yii2tech\ar\softdelete\SoftDeleteQueryBehavior;

/**
 * This is the model class for table "order_product".
 *
 * @property int $id
 * @property int $order_id
 * @property int $product_id
 * @property int $store_id
 * @property float $count
 * @property float $total_product_amount
 * @property float $discount
 * @property int $count_type
 * @property int $price_number
 * @property int $amount
 * @property int $created_at
 * @property int|null $created_by
 * @property int $updated_at
 * @property int|null $updated_by
 * @property int|null $isDeleted
 */
class OrderProduct extends \common\components\BaseModel
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'count', 'price_number', 'amount'], 'required'],
            [['order_id', 'product_id', 'count_type', 'created_at', 'created_by', 'updated_at', 'updated_by', 'isDeleted','store_id'], 'integer'],
            [['count'], 'number'],
            [['product_id'], 'checkInventory'],
            [['product_id'], 'checkDuplicate'],
            [['total_product_amount', 'discount'], 'double'],
        ];
    }

    public function checkInventory($attr, $params) {

        if (   isset($this->product_id)) {
            $item_inventory_count = InventoryOrderProduct::find()->where(['store_id'=>$this->store_id,'product_id'=>$this->product_id])->sum('count') ?? 0;
            $item_order_count = OrderProduct::find()->where(['store_id'=>$this->store_id,'product_id'=>$this->product_id])->andWhere(['<>','id',$this->id??0])->sum('count')?? 0 ;

            $total = $item_inventory_count- $item_order_count;

            $current_count = !empty($this->count)?$this->count:0;
            if (($total - $current_count)<0) {

                $this->addError($attr, 'لا توجد هذه الكمية (الموجود هو '.$total.')');
            }
        }
    }

    public function checkDuplicate($attr, $params) {

        if (isset($this->product_id)) {
            $item_order = OrderProduct::find()->where(['order_id'=>$this->order_id,'product_id'=>$this->product_id])->andWhere(['<>','id',$this->id??0])->one() ;

            if ($item_order) {
                $this->addError($attr, 'لا يمكنك اضافة نفس المادة اكثر من مرة');
            }
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        $old_product = $changedAttributes['product_id']??null;
        CustomFunc::calculateProductCount($this->store_id, $this->product_id,$old_product);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        CustomFunc::calculateProductCount($this->store_id,$this->product_id);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::className(),
                'softDeleteAttributeValues' => [
                    'isDeleted' => true
                ],
            ],
            TimestampBehavior::className(),
            BlameableBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function beforeValidate()
    {
        if (!empty($this->price_number) && !empty($this->product)) {
            $price_feild = 'price_' . $this->price_number;
            $this->amount = $this->product->$price_feild;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' =>  'الرقم',
            'order_id' =>  'رقم الطلب',
            'product_id' =>  'المادة',
            'price_number' =>  'السعر',
            'amount' =>  'السعر الفردي',
            'count' =>  'العدد',
            'store_id' =>  'المحل',
            'count_type' =>  'نوع العدد',
            'created_at' =>  'تاريخ الانشاء',
            'created_by' =>  'الشخص المنشئ',
            'updated_at' =>  'تاريخ التعديل',
            'updated_by' =>  'الشخص المعدل',
            'discount' =>  'الخصم',
            'total_product_amount' =>  'السعر الاجمالي',
        ];
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\OrderProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        $query = new \common\models\query\OrderProductQuery(get_called_class());
        $query->attachBehavior('softDelete', SoftDeleteQueryBehavior::className());
        return $query;
    }

    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }
    public function getProductTitle()
    {
        return $this->product ? $this->product->title : '';
    }
    public function getOrder()
    {
        return $this->hasOne(Order::className(), ['id' => 'order_id']);
    }

    public function getPriceList()
    {
        $prices = [];
        if(Yii::$app->user->can('سعر بيع 1')){
            $prices[1]= 1;
        }
        if(Yii::$app->user->can('سعر بيع 2')){
            $prices[2]= 2;
        }
        if(Yii::$app->user->can('سعر بيع 3')){
            $prices[3]= 3;
        }
        if(Yii::$app->user->can('سعر بيع 4')){
            $prices[4]= 4;
        }


        return $prices;

    }
    public function getStoreTitle()
    {
        return Constants::getStoreName($this->store_id);
    }

}
