<?php

namespace common\models;

use common\components\Constants;
use common\components\CustomFunc;
use Yii;
use yii\behaviors\AttributeTypecastBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;
use yii2tech\ar\softdelete\SoftDeleteQueryBehavior;

/**
 * This is the model class for table "order_product".
 *
 * @property int $id
 * @property int $order_id
 * @property int $product_id
 * @property int $store_id
 * @property float $items_cost
 * @property float $count
 * @property float $total_product_amount
 * @property float $orignal_cost
 * @property float $discount
 * @property int $count_type
 * @property int $price_number
 * @property int $amount
 * @property int $created_at
 * @property int|null $created_by
 * @property int $updated_at
 * @property int|null $updated_by
 * @property int|null $isDeleted
 */
class OrderProduct extends \common\components\BaseModel
{
    public $ready_to_deliver ;
    public $count_type_name ;

    public $item_location ;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'count', 'price_number', 'amount'], 'required'],
            [['order_id', 'product_id', 'count_type', 'created_at', 'created_by', 'updated_at', 'updated_by', 'isDeleted','store_id'], 'integer'],
            [['count'], 'number'],
            [['count_type_name','items_cost'], 'safe'],
            [['ready_to_deliver'], 'checkReady'],
            [['product_id'], 'checkInventory'],
            [['product_id'], 'checkDuplicate'],
            [['total_product_amount', 'discount','orignal_cost'], 'double'],
        ];
    }

    public function checkInventory($attr, $params) {

        if (   isset($this->product_id)) {
            $store_id = $this->store_id ;
            $product_id = $this->product_id;

            $item_inventory_count = InventoryOrderProduct::find()->select('count')->where(['store_id'=>$store_id,'product_id'=>$product_id])->sum('count') ?? 0;
            $q = OrderProduct::find()->select('count')->where(['store_id'=>$store_id,'product_id'=>$product_id]);
            if($this->order_id)
            {
                $q->andWhere(['<>','order_id',$this->order_id]);
            }

            $item_order_count = $q->sum('count')?? 0 ;

            $returned = Returns::find()->select('count')->joinWith('order')->where(['order.store_id'=>$store_id,'product_id'=>$product_id])->sum('count');
            $damaged_returned = Damaged::find()->select('count')->joinWith('order')->where(['order.store_id'=>$store_id,'product_id'=>$product_id,'status'=>Damaged::STATUS_RETURNED])->sum('count');
            $damaged_inactive = Damaged::find()->select('count')->joinWith('order')->where(['order.store_id'=>$store_id,'product_id'=>$product_id])->andWhere(['<>','status',Damaged::STATUS_REPLACED]) ->sum('count');
            $transformTo =  TransferOrder::find()->select('count')->where(['to'=>$store_id,'product_id'=>$product_id])->sum('count');
            $transformFrom =  TransferOrder::find()->select('count')->where(['from'=>$store_id,'product_id'=>$product_id])->sum('count');
            $SeparationsTo = Separations::find()->select('count_to')->where(['store_id' => $store_id, 'product_id_to' => $product_id])->sum('count_to');
            $SeparationsFrom = Separations::find()->select('count_from')->where(['store_id' => $store_id, 'product_id_from' => $product_id])->sum('count_from');
            

            $total = (double) $item_inventory_count + (double) $returned - (double) $item_order_count + (double) $damaged_returned - (double) $damaged_inactive - (double) $transformFrom + (double) $transformTo - (double) $SeparationsFrom + (double) $SeparationsTo;

            $current_count = !empty($this->count)?$this->count:0;
            if (($total - $current_count)<0) {

               $this->addError($attr, 'لا توجد هذه الكمية (الموجود هو '.$total.')');
            }
        }
    }
    public function checkReady($attr, $params) {

        if (   empty($this->ready_to_deliver) && $this->isNewRecord) {
            $this->addError($attr, 'يجب تجهيز هذه المادة');
        }
    }

    public function checkDuplicate($attr, $params) {

        if (isset($this->product_id)) {
            $item_order = OrderProduct::find()->where(['order_id'=>$this->order_id,'product_id'=>$this->product_id])->andWhere(['<>','id',$this->id??0])->one() ;

            if ($item_order) {
                $this->addError($attr, 'لا يمكنك اضافة نفس المادة اكثر من مرة');
            }
        }
    }
    

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if(!empty($changedAttributes['product_id']) || !empty($changedAttributes['count']) || $insert )
        {

            $old_product = $changedAttributes['product_id']?? null;
            CustomFunc::calculateProductCount($this->store_id, $this->product_id,$old_product);
        }


    }

    public function afterDelete()
    {
        CustomFunc::calculateProductCount($this->store_id,$this->product_id);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::className(),
                'softDeleteAttributeValues' => [
                    'isDeleted' => true
                ],
            ],
            'typecast' => [
                'class' => AttributeTypecastBehavior::class,
                'attributeTypes' => [
                    'product_id' => AttributeTypecastBehavior::TYPE_INTEGER,
                    'count' => AttributeTypecastBehavior::TYPE_FLOAT,
                ],
                'typecastAfterValidate' => true,
                'typecastBeforeSave' => false,
                'typecastAfterFind' => false,
            ],
            TimestampBehavior::className(),
            BlameableBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function beforeValidate()
    {
        if (!empty($this->price_number) && !empty($this->product)) {
            $price_feild = 'price_' . $this->price_number;
            $this->amount = $this->product->$price_feild;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' =>  'الرقم',
            'order_id' =>  'رقم الطلب',
            'product_id' =>  'المادة',
            'price_number' =>  'السعر',
            'amount' =>  'السعر الفردي',
            'count' =>  'العدد',
            'store_id' =>  'المحل',
            'count_type' =>  'نوع العدد',
            'created_at' =>  'تاريخ الانشاء',
            'created_by' =>  'الشخص المنشئ',
            'updated_at' =>  'تاريخ التعديل',
            'updated_by' =>  'الشخص المعدل',
            'discount' =>  'الخصم',
            'total_product_amount' =>  'السعر الاجمالي',
        ];
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\OrderProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        $query = new \common\models\query\OrderProductQuery(get_called_class());
        $query->attachBehavior('softDelete', SoftDeleteQueryBehavior::className());
        return $query;
    }

    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }
    public function getProductTitle()
    {
        return $this->product ? $this->product->title : '';
    }

    public function getProductCountType()
    {
        return $this->product ? $this->product->getCountTypeName('count_type') : '';
    }
    public function getOrder()
    {
        return $this->hasOne(Order::className(), ['id' => 'order_id']);
    }

    public function getPriceList()
    {
        $prices = [];
        if(Yii::$app->user->can('سعر بيع 1')){
            $prices[1]= 1;
        }
        if(Yii::$app->user->can('سعر بيع 2')){
            $prices[2]= 2;
        }
        if(Yii::$app->user->can('سعر بيع 3')){
            $prices[3]= 3;
        }
        if(Yii::$app->user->can('سعر بيع 4')){
            $prices[4]= 4;
        }


        return $prices;

    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord)
        {
            $this->items_cost =  $this->product->price * $this->count;

            if($this->product->count_next){
                $this->product->count_next -= $this->count;
                if($this->product->count_next <= 0)
                {
                    $this->product->count_next = null ;
                    if($this->product->price_next){
                        $this->product->price = $this->product->price_next;
                        $this->product->price_next= null;
                    }
                    if($this->product->price_1_next){
                        $this->product->price_1 = $this->product->price_1_next;
                        $this->product->price_1_next = null;
                    }
                    if($this->product->price_2_next){
                        $this->product->price_2 = $this->product->price_2_next;
                        $this->product->price_2_next = null;
                    }
                    if($this->product->price_3_next){
                        $this->product->price_3 = $this->product->price_3_next;
                        $this->product->price_3_next = null;
                    }
                    if($this->product->price_4_next){
                        $this->product->price_4 = $this->product->price_4_next;
                        $this->product->price_4_next = null;
                    }


                }
                $this->product->save(false);
            }

        }
        return parent::beforeSave($insert);
    }
    public function getStoreTitle()
    {
        return Store::findOne($this->store_id)->name??'';
    }

}
