<?php
namespace dashboard\components;

use yii\web\Controller;

class BaseController extends Controller
{

    public function beforeAction($action)
    {
        print_r(\Yii::$app->user);die;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}